title: code note
email: info@byeolbit.com
author:
    gravatar_md5: c6b0a85884aef260ae58de1275258ef0

description: Space for memo codes
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://byeolbit.github.io" # the base hostname & protocol for your site
twitter_username: byeolbit
github_username: byeolbit

# Build settings
markdown: kramdown
highlighter: rouge
